server:
  port: 8082

spring:
  application:
    name: lending-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-lending}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lending

catalog:
  base-url: ${CATALOG_BASE_URL:http://localhost:8081}
